-- MySQL Script generated by MySQL Workbench
-- Thu Apr 13 15:24:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecomdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecomdb` ;

-- -----------------------------------------------------
-- Schema ecomdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecomdb` DEFAULT CHARACTER SET utf8 ;
USE `ecomdb` ;

-- -----------------------------------------------------
-- Table `ecomdb`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`address` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `streetno` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NULL,
  `apartment_no` VARCHAR(45) NULL,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` TIMESTAMP NULL,
  `deleted_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecomdb`.`user_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`user_address` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`user_address` (
  `id` INT NULL AUTO_INCREMENT,
  `idUser` INT NULL,
  `idAddress` INT NULL,
  `contact_name` VARCHAR(45) NOT NULL,
  `contact_phone` VARCHAR(45) NOT NULL,
  `contact_email` VARCHAR(45) NULL,
  `cretated_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` TIMESTAMP NULL,
  `deleted_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_userid_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_useraddr_addrid_idx` (`idAddress` ASC) VISIBLE,
  CONSTRAINT `fk_useraddr_userid`
    FOREIGN KEY (`idUser`)
    REFERENCES `ecomdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_useraddr_addrid`
    FOREIGN KEY (`idAddress`)
    REFERENCES `ecomdb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`user` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `default_usr_address_id` INT NULL DEFAULT -1,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` TIMESTAMP NULL,
  `deleted_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_user_defaultAddr_idx` (`default_usr_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_defaultAddr`
    FOREIGN KEY (`default_usr_address_id`)
    REFERENCES `ecomdb`.`user_address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomdb`.`user_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`user_payment` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`user_payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `payment_type` VARCHAR(45) NOT NULL,
  `service_provider` VARCHAR(45) NOT NULL,
  `account_number` VARCHAR(45) NOT NULL,
  `expiry` DATE NOT NULL,
  `service_reference_number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_userid_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_payment_userid`
    FOREIGN KEY (`idUser`)
    REFERENCES `ecomdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomdb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`category` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  `category_desc` VARCHAR(45) NULL,
  `parent_category` INT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecomdb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`product` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`product` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `price` DECIMAL NOT NULL,
  `available` TINYINT NOT NULL,
  `categoryid` INT NULL,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` TIMESTAMP NULL,
  `deleted_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_cateid_idx` (`categoryid` ASC) VISIBLE,
  CONSTRAINT `fk_product_cateid`
    FOREIGN KEY (`categoryid`)
    REFERENCES `ecomdb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomdb`.`management`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`management` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`management` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contact_person` VARCHAR(45) NULL,
  `company_name` VARCHAR(45) NOT NULL,
  `contact_number` VARCHAR(45) NULL,
  `contact_email` VARCHAR(45) NULL,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` TIMESTAMP NULL,
  `deleted_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecomdb`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`inventory` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_address` INT NULL,
  `id_management` INT NULL,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` TIMESTAMP NULL,
  `deleted_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inv_addr_idx` (`id_address` ASC) VISIBLE,
  INDEX `fk_inv_man_idx` (`id_management` ASC) VISIBLE,
  CONSTRAINT `fk_inv_addr`
    FOREIGN KEY (`id_address`)
    REFERENCES `ecomdb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_man`
    FOREIGN KEY (`id_management`)
    REFERENCES `ecomdb`.`management` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecomdb`.`product_inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`product_inventory` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`product_inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_product` INT NOT NULL,
  `id_inventory` INT NULL,
  `quantity` INT NOT NULL,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` TIMESTAMP NULL,
  `deleted_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_prodinv_prodid_idx` (`id_product` ASC) VISIBLE,
  INDEX `fk_prodinv_invid_idx` (`id_inventory` ASC) VISIBLE,
  CONSTRAINT `fk_prodinv_prodid`
    FOREIGN KEY (`id_product`)
    REFERENCES `ecomdb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prodinv_invid`
    FOREIGN KEY (`id_inventory`)
    REFERENCES `ecomdb`.`inventory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecomdb`.`inventory_management`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`inventory_management` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`inventory_management` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inventory_id` INT NOT NULL,
  `management_id` INT NOT NULL,
  `associated_cost` DECIMAL NOT NULL,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` TIMESTAMP NULL,
  `deleted_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `inventory_id_UNIQUE` (`inventory_id` ASC) VISIBLE,
  INDEX `fk_inventman_man_idx` (`management_id` ASC) VISIBLE,
  CONSTRAINT `fk_inventman_inv`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `ecomdb`.`inventory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventman_man`
    FOREIGN KEY (`management_id`)
    REFERENCES `ecomdb`.`management` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecomdb`.`discount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`discount` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`discount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `discount_method` VARCHAR(45) NOT NULL,
  `discount_amount` DECIMAL NULL,
  `discount_percentage` DECIMAL NULL,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` TIMESTAMP NULL,
  `deleted_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecomdb`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`cart` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `total` DECIMAL NOT NULL,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` TIMESTAMP NULL,
  `deleted_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cart_uid_idx` (`userid` ASC) VISIBLE,
  CONSTRAINT `fk_cart_uid`
    FOREIGN KEY (`userid`)
    REFERENCES `ecomdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecomdb`.`cart_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`cart_product` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`cart_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `cartid` INT NOT NULL,
  `quantity` INT NOT NULL,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` TIMESTAMP NULL,
  `deleted_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cartprod_prodid_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_cartprod_cartid_idx` (`cartid` ASC) VISIBLE,
  CONSTRAINT `fk_cartprod_prodid`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecomdb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartprod_cartid`
    FOREIGN KEY (`cartid`)
    REFERENCES `ecomdb`.`cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecomdb`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`order` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `amount_due` DECIMAL NOT NULL,
  `amount_paid` DECIMAL NOT NULL,
  `shipto_useraddressid` INT NOT NULL,
  `paymentid` INT NOT NULL,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` TIMESTAMP NULL,
  `deleted_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_useraddrid_idx` (`shipto_useraddressid` ASC) VISIBLE,
  INDEX `fk_order_userid_idx` (`userid` ASC) VISIBLE,
  INDEX `fk_order_paymentid_idx` (`paymentid` ASC, `userid` ASC) VISIBLE,
  CONSTRAINT `fk_order_userid`
    FOREIGN KEY (`userid`)
    REFERENCES `ecomdb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_useraddrid`
    FOREIGN KEY (`shipto_useraddressid`)
    REFERENCES `ecomdb`.`user_address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_paymentid`
    FOREIGN KEY (`paymentid` , `userid`)
    REFERENCES `ecomdb`.`user_payment` (`id` , `idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecomdb`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`order_items` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`order_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productid` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT 1,
  `discountid` INT NULL DEFAULT -1,
  `orderid` INT NOT NULL,
  `created_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_time` TIMESTAMP NULL,
  `deleted_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orderitem_prodid_idx` (`productid` ASC) VISIBLE,
  INDEX `fk_orderitem_discountid_idx` (`discountid` ASC) VISIBLE,
  INDEX `fk_orderitem_orderid_idx` (`orderid` ASC) VISIBLE,
  CONSTRAINT `fk_orderitem_prodid`
    FOREIGN KEY (`productid`)
    REFERENCES `ecomdb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderitem_discountid`
    FOREIGN KEY (`discountid`)
    REFERENCES `ecomdb`.`discount` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderitem_orderid`
    FOREIGN KEY (`orderid`)
    REFERENCES `ecomdb`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecomdb`.`category_subcategories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`category_subcategories` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`category_subcategories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `child_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categoryhier_cateid_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_categoryhier_childid_idx` (`child_id` ASC) VISIBLE,
  CONSTRAINT `fk_categoryhier_cateid`
    FOREIGN KEY (`category_id`)
    REFERENCES `ecomdb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoryhier_childid`
    FOREIGN KEY (`child_id`)
    REFERENCES `ecomdb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecomdb`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`tag` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecomdb`.`keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`keyword` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`keyword` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomdb`.`tag_keyword`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`tag_keyword` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`tag_keyword` (
  `idtag_keyword` INT NOT NULL AUTO_INCREMENT,
  `tagid` INT NOT NULL,
  `keywordid` INT NOT NULL,
  PRIMARY KEY (`idtag_keyword`),
  INDEX `fk_tagkey_tagid_idx` (`tagid` ASC) VISIBLE,
  INDEX `fk_tagkey_keyid_idx` (`keywordid` ASC) VISIBLE,
  CONSTRAINT `fk_tagkey_tagid`
    FOREIGN KEY (`tagid`)
    REFERENCES `ecomdb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tagkey_keyid`
    FOREIGN KEY (`keywordid`)
    REFERENCES `ecomdb`.`keyword` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomdb`.`product_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`product_tag` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`product_tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productid` INT NOT NULL,
  `tagid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prodtag_prodid_idx` (`productid` ASC) VISIBLE,
  INDEX `fk_prodtag_tagid_idx` (`tagid` ASC) VISIBLE,
  CONSTRAINT `fk_prodtag_prodid`
    FOREIGN KEY (`productid`)
    REFERENCES `ecomdb`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prodtag_tagid`
    FOREIGN KEY (`tagid`)
    REFERENCES `ecomdb`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomdb`.`shipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`shipment` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`shipment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orderid` INT NOT NULL,
  `from_inventoryid` INT NOT NULL,
  `to_usraddressid` INT NOT NULL,
  `logistics_provider` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ship_orderid_idx` (`orderid` ASC) VISIBLE,
  INDEX `fk_ship_frominvid_idx` (`from_inventoryid` ASC) VISIBLE,
  INDEX `fk_ship_tousraddrid_idx` (`to_usraddressid` ASC) VISIBLE,
  CONSTRAINT `fk_ship_orderid`
    FOREIGN KEY (`orderid`)
    REFERENCES `ecomdb`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ship_frominvid`
    FOREIGN KEY (`from_inventoryid`)
    REFERENCES `ecomdb`.`inventory` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ship_tousraddrid`
    FOREIGN KEY (`to_usraddressid`)
    REFERENCES `ecomdb`.`user_address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecomdb`.`order_shipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecomdb`.`order_shipment` ;

CREATE TABLE IF NOT EXISTS `ecomdb`.`order_shipment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orderid` INT NOT NULL,
  `shipmentid` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `shipmentid_UNIQUE` (`shipmentid` ASC) VISIBLE,
  INDEX `fk_ordership_orderid_idx` (`orderid` ASC) VISIBLE,
  CONSTRAINT `fk_ordership_orderid`
    FOREIGN KEY (`orderid`)
    REFERENCES `ecomdb`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordership_shipid`
    FOREIGN KEY (`shipmentid`)
    REFERENCES `ecomdb`.`shipment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
